//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//*****************************************************************************
//
// Notes on the ETW event code generated by MC:
//
// - Structures and arrays of structures are treated as an opaque binary blob.
//   The caller is responsible for packing the data for the structure into a
//   single region of memory, with no padding between values. The macro will
//   have an extra parameter for the length of the blob.
// - Arrays of nul-terminated strings must be packed by the caller into a
//   single binary blob containing the correct number of strings, with a nul
//   after each string. The size of the blob is specified in characters, and
//   includes the final nul.
// - Arrays of SID are treated as a single binary blob. The caller is
//   responsible for packing the SID values into a single region of memory with
//   no padding.
// - The length attribute on the data element in the manifest is significant
//   for values with intype win:UnicodeString, win:AnsiString, or win:Binary.
//   The length attribute must be specified for win:Binary, and is optional for
//   win:UnicodeString and win:AnsiString (if no length is given, the strings
//   are assumed to be nul-terminated). For win:UnicodeString, the length is
//   measured in characters, not bytes.
// - For an array of win:UnicodeString, win:AnsiString, or win:Binary, the
//   length attribute applies to every value in the array, so every value in
//   the array must have the same length. The values in the array are provided
//   to the macro via a single pointer -- the caller is responsible for packing
//   all of the values into a single region of memory with no padding between
//   values.
// - Values of type win:CountedUnicodeString, win:CountedAnsiString, and
//   win:CountedBinary can be generated and collected on Vista or later.
//   However, they may not decode properly without the Windows 10 2018 Fall
//   Update.
// - Arrays of type win:CountedUnicodeString, win:CountedAnsiString, and
//   win:CountedBinary must be packed by the caller into a single region of
//   memory. The format for each item is a UINT16 byte-count followed by that
//   many bytes of data. When providing the array to the generated macro, you
//   must provide the total size of the packed array data, including the UINT16
//   sizes for each item. In the case of win:CountedUnicodeString, the data
//   size is specified in WCHAR (16-bit) units. In the case of
//   win:CountedAnsiString and win:CountedBinary, the data size is specified in
//   bytes.
//
//*****************************************************************************

#include <wmistr.h>
#include <evntrace.h>
#include <evntprov.h>

#ifndef ETW_INLINE
  #ifdef _ETW_KM_
    // In kernel mode, save stack space by never inlining templates.
    #define ETW_INLINE DECLSPEC_NOINLINE __inline
  #else
    // In user mode, save code size by inlining templates as appropriate.
    #define ETW_INLINE __inline
  #endif
#endif // ETW_INLINE

#if defined(__cplusplus)
extern "C" {
#endif

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// MCGEN_USE_KERNEL_MODE_APIS macro:
// Controls whether the generated code uses kernel-mode or user-mode APIs.
// - Set to 0 to use Windows user-mode APIs such as EventRegister.
// - Set to 1 to use Windows kernel-mode APIs such as EtwRegister.
// Default is based on whether the _ETW_KM_ macro is defined (i.e. by wdm.h).
// Note that the APIs can also be overridden directly, e.g. by setting the
// MCGEN_EVENTWRITETRANSFER or MCGEN_EVENTREGISTER macros.
//
#ifndef MCGEN_USE_KERNEL_MODE_APIS
  #ifdef _ETW_KM_
    #define MCGEN_USE_KERNEL_MODE_APIS 1
  #else
    #define MCGEN_USE_KERNEL_MODE_APIS 0
  #endif
#endif // MCGEN_USE_KERNEL_MODE_APIS

//
// MCGEN_HAVE_EVENTSETINFORMATION macro:
// Controls how McGenEventSetInformation uses the EventSetInformation API.
// - Set to 0 to disable the use of EventSetInformation
//   (McGenEventSetInformation will always return an error).
// - Set to 1 to directly invoke MCGEN_EVENTSETINFORMATION.
// - Set to 2 to to locate EventSetInformation at runtime via GetProcAddress
//   (user-mode) or MmGetSystemRoutineAddress (kernel-mode).
// Default is determined as follows:
// - If MCGEN_EVENTSETINFORMATION has been customized, set to 1
//   (i.e. use MCGEN_EVENTSETINFORMATION).
// - Else if the target OS version has EventSetInformation, set to 1
//   (i.e. use MCGEN_EVENTSETINFORMATION).
// - Else set to 2 (i.e. try to dynamically locate EventSetInformation).
// Note that an McGenEventSetInformation function will only be generated if one
// or more provider in a manifest has provider traits.
//
#ifndef MCGEN_HAVE_EVENTSETINFORMATION
  #ifdef MCGEN_EVENTSETINFORMATION             // if MCGEN_EVENTSETINFORMATION has been customized,
    #define MCGEN_HAVE_EVENTSETINFORMATION   1 //   directly invoke MCGEN_EVENTSETINFORMATION(...).
  #elif MCGEN_USE_KERNEL_MODE_APIS             // else if using kernel-mode APIs,
    #if NTDDI_VERSION >= 0x06040000            //   if target OS is Windows 10 or later,
      #define MCGEN_HAVE_EVENTSETINFORMATION 1 //     directly invoke MCGEN_EVENTSETINFORMATION(...).
    #else                                      //   else
      #define MCGEN_HAVE_EVENTSETINFORMATION 2 //     find "EtwSetInformation" via MmGetSystemRoutineAddress.
    #endif                                     // else (using user-mode APIs)
  #else                                        //   if target OS and SDK is Windows 8 or later,
    #if WINVER >= 0x0602 && defined(EVENT_FILTER_TYPE_SCHEMATIZED)
      #define MCGEN_HAVE_EVENTSETINFORMATION 1 //     directly invoke MCGEN_EVENTSETINFORMATION(...).
    #else                                      //   else
      #define MCGEN_HAVE_EVENTSETINFORMATION 2 //     find "EventSetInformation" via GetModuleHandleExW/GetProcAddress.
    #endif
  #endif
#endif // MCGEN_HAVE_EVENTSETINFORMATION

//
// MCGEN Override Macros
//
// The following override macros may be defined before including this header
// to control the APIs used by this header:
//
// - MCGEN_EVENTREGISTER
// - MCGEN_EVENTUNREGISTER
// - MCGEN_EVENTSETINFORMATION
// - MCGEN_EVENTWRITETRANSFER
//
// If the the macro is undefined, the MC implementation will default to the
// corresponding ETW APIs. For example, if the MCGEN_EVENTREGISTER macro is
// undefined, the EventRegister[MyProviderName] macro will use EventRegister
// in user mode and will use EtwRegister in kernel mode.
//
// To prevent issues from conflicting definitions of these macros, the value
// of the override macro will be used as a suffix in certain internal function
// names. Because of this, the override macros must follow certain rules:
//
// - The macro must be defined before any MC-generated header is included and
//   must not be undefined or redefined after any MC-generated header is
//   included. Different translation units (i.e. different .c or .cpp files)
//   may set the macros to different values, but within a translation unit
//   (within a single .c or .cpp file), the macro must be set once and not
//   changed.
// - The override must be an object-like macro, not a function-like macro
//   (i.e. the override macro must not have a parameter list).
// - The override macro's value must be a simple identifier, i.e. must be
//   something that starts with a letter or '_' and contains only letters,
//   numbers, and '_' characters.
// - If the override macro's value is the name of a second object-like macro,
//   the second object-like macro must follow the same rules. (The override
//   macro's value can also be the name of a function-like macro, in which
//   case the function-like macro does not need to follow the same rules.)
//
// For example, the following will cause compile errors:
//
//   #define MCGEN_EVENTWRITETRANSFER MyNamespace::MyClass::MyFunction // Value has non-identifier characters (colon).
//   #define MCGEN_EVENTWRITETRANSFER GetEventWriteFunctionPointer(7)  // Value has non-identifier characters (parentheses).
//   #define MCGEN_EVENTWRITETRANSFER(h,e,a,r,c,d) EventWrite(h,e,c,d) // Override is defined as a function-like macro.
//   #define MY_OBJECT_LIKE_MACRO     MyNamespace::MyClass::MyEventWriteFunction
//   #define MCGEN_EVENTWRITETRANSFER MY_OBJECT_LIKE_MACRO // Evaluates to something with non-identifier characters (colon).
//
// The following would be ok:
//
//   #define MCGEN_EVENTWRITETRANSFER  MyEventWriteFunction1  // OK, suffix will be "MyEventWriteFunction1".
//   #define MY_OBJECT_LIKE_MACRO      MyEventWriteFunction2
//   #define MCGEN_EVENTWRITETRANSFER  MY_OBJECT_LIKE_MACRO   // OK, suffix will be "MyEventWriteFunction2".
//   #define MY_FUNCTION_LIKE_MACRO(h,e,a,r,c,d) MyNamespace::MyClass::MyEventWriteFunction3(h,e,c,d)
//   #define MCGEN_EVENTWRITETRANSFER  MY_FUNCTION_LIKE_MACRO // OK, suffix will be "MY_FUNCTION_LIKE_MACRO".
//
#ifndef MCGEN_EVENTREGISTER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTREGISTER        EtwRegister
  #else
    #define MCGEN_EVENTREGISTER        EventRegister
  #endif
#endif // MCGEN_EVENTREGISTER
#ifndef MCGEN_EVENTUNREGISTER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTUNREGISTER      EtwUnregister
  #else
    #define MCGEN_EVENTUNREGISTER      EventUnregister
  #endif
#endif // MCGEN_EVENTUNREGISTER
#ifndef MCGEN_EVENTSETINFORMATION
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTSETINFORMATION  EtwSetInformation
  #else
    #define MCGEN_EVENTSETINFORMATION  EventSetInformation
  #endif
#endif // MCGEN_EVENTSETINFORMATION
#ifndef MCGEN_EVENTWRITETRANSFER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTWRITETRANSFER   EtwWriteTransfer
  #else
    #define MCGEN_EVENTWRITETRANSFER   EventWriteTransfer
  #endif
#endif // MCGEN_EVENTWRITETRANSFER

//
// MCGEN_EVENT_ENABLED macro:
// Override to control how the EventWrite[EventName] macros determine whether
// an event is enabled. The default behavior is for EventWrite[EventName] to
// use the EventEnabled[EventName] macros.
//
#ifndef MCGEN_EVENT_ENABLED
#define MCGEN_EVENT_ENABLED(EventName) EventEnabled##EventName()
#endif

//
// MCGEN_EVENT_ENABLED_FORCONTEXT macro:
// Override to control how the EventWrite[EventName]_ForContext macros
// determine whether an event is enabled. The default behavior is for
// EventWrite[EventName]_ForContext to use the
// EventEnabled[EventName]_ForContext macros.
//
#ifndef MCGEN_EVENT_ENABLED_FORCONTEXT
#define MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EventName) EventEnabled##EventName##_ForContext(pContext)
#endif

//
// MCGEN_ENABLE_CHECK macro:
// Determines whether the specified event would be considered as enabled
// based on the state of the specified context. Slightly faster than calling
// McGenEventEnabled directly.
//
#ifndef MCGEN_ENABLE_CHECK
#define MCGEN_ENABLE_CHECK(Context, Descriptor) (Context.IsEnabled && McGenEventEnabled(&Context, &Descriptor))
#endif

#if !defined(MCGEN_TRACE_CONTEXT_DEF)
#define MCGEN_TRACE_CONTEXT_DEF
// This structure is for use by MC-generated code and should not be used directly.
typedef struct _MCGEN_TRACE_CONTEXT
{
    TRACEHANDLE            RegistrationHandle;
    TRACEHANDLE            Logger;      // Used as pointer to provider traits.
    ULONGLONG              MatchAnyKeyword;
    ULONGLONG              MatchAllKeyword;
    ULONG                  Flags;
    ULONG                  IsEnabled;
    UCHAR                  Level;
    UCHAR                  Reserve;
    USHORT                 EnableBitsCount;
    PULONG                 EnableBitMask;
    const ULONGLONG*       EnableKeyWords;
    const UCHAR*           EnableLevel;
} MCGEN_TRACE_CONTEXT, *PMCGEN_TRACE_CONTEXT;
#endif // MCGEN_TRACE_CONTEXT_DEF

#if !defined(MCGEN_LEVEL_KEYWORD_ENABLED_DEF)
#define MCGEN_LEVEL_KEYWORD_ENABLED_DEF
//
// Determines whether an event with a given Level and Keyword would be
// considered as enabled based on the state of the specified context.
// Note that you may want to use MCGEN_ENABLE_CHECK instead of calling this
// function directly.
//
FORCEINLINE
BOOLEAN
McGenLevelKeywordEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ UCHAR Level,
    _In_ ULONGLONG Keyword
    )
{
    //
    // Check if the event Level is lower than the level at which
    // the channel is enabled.
    // If the event Level is 0 or the channel is enabled at level 0,
    // all levels are enabled.
    //

    if ((Level <= EnableInfo->Level) || // This also covers the case of Level == 0.
        (EnableInfo->Level == 0)) {

        //
        // Check if Keyword is enabled
        //

        if ((Keyword == (ULONGLONG)0) ||
            ((Keyword & EnableInfo->MatchAnyKeyword) &&
             ((Keyword & EnableInfo->MatchAllKeyword) == EnableInfo->MatchAllKeyword))) {
            return TRUE;
        }
    }

    return FALSE;
}
#endif // MCGEN_LEVEL_KEYWORD_ENABLED_DEF

#if !defined(MCGEN_EVENT_ENABLED_DEF)
#define MCGEN_EVENT_ENABLED_DEF
//
// Determines whether the specified event would be considered as enabled based
// on the state of the specified context. Note that you may want to use
// MCGEN_ENABLE_CHECK instead of calling this function directly.
//
FORCEINLINE
BOOLEAN
McGenEventEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ PCEVENT_DESCRIPTOR EventDescriptor
    )
{
    return McGenLevelKeywordEnabled(EnableInfo, EventDescriptor->Level, EventDescriptor->Keyword);
}
#endif // MCGEN_EVENT_ENABLED_DEF

#if !defined(MCGEN_CONTROL_CALLBACK)
#define MCGEN_CONTROL_CALLBACK

// This function is for use by MC-generated code and should not be used directly.
DECLSPEC_NOINLINE __inline
VOID
__stdcall
McGenControlCallbackV2(
    _In_ LPCGUID SourceId,
    _In_ ULONG ControlCode,
    _In_ UCHAR Level,
    _In_ ULONGLONG MatchAnyKeyword,
    _In_ ULONGLONG MatchAllKeyword,
    _In_opt_ PEVENT_FILTER_DESCRIPTOR FilterData,
    _Inout_opt_ PVOID CallbackContext
    )
/*++

Routine Description:

    This is the notification callback for Windows Vista and later.

Arguments:

    SourceId - The GUID that identifies the session that enabled the provider.

    ControlCode - The parameter indicates whether the provider
                  is being enabled or disabled.

    Level - The level at which the event is enabled.

    MatchAnyKeyword - The bitmask of keywords that the provider uses to
                      determine the category of events that it writes.

    MatchAllKeyword - This bitmask additionally restricts the category
                      of events that the provider writes.

    FilterData - The provider-defined data.

    CallbackContext - The context of the callback that is defined when the provider
                      called EtwRegister to register itself.

Remarks:

    ETW calls this function to notify provider of enable/disable

--*/
{
    PMCGEN_TRACE_CONTEXT Ctx = (PMCGEN_TRACE_CONTEXT)CallbackContext;
    ULONG Ix;
#ifndef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    UNREFERENCED_PARAMETER(SourceId);
    UNREFERENCED_PARAMETER(FilterData);
#endif

    if (Ctx == NULL) {
        return;
    }

    switch (ControlCode) {

        case EVENT_CONTROL_CODE_ENABLE_PROVIDER:
            Ctx->Level = Level;
            Ctx->MatchAnyKeyword = MatchAnyKeyword;
            Ctx->MatchAllKeyword = MatchAllKeyword;
            Ctx->IsEnabled = EVENT_CONTROL_CODE_ENABLE_PROVIDER;

            for (Ix = 0; Ix < Ctx->EnableBitsCount; Ix += 1) {
                if (McGenLevelKeywordEnabled(Ctx, Ctx->EnableLevel[Ix], Ctx->EnableKeyWords[Ix]) != FALSE) {
                    Ctx->EnableBitMask[Ix >> 5] |= (1 << (Ix % 32));
                } else {
                    Ctx->EnableBitMask[Ix >> 5] &= ~(1 << (Ix % 32));
                }
            }
            break;

        case EVENT_CONTROL_CODE_DISABLE_PROVIDER:
            Ctx->IsEnabled = EVENT_CONTROL_CODE_DISABLE_PROVIDER;
            Ctx->Level = 0;
            Ctx->MatchAnyKeyword = 0;
            Ctx->MatchAllKeyword = 0;
            if (Ctx->EnableBitsCount > 0) {
#pragma warning(suppress: 26451) // Arithmetic overflow cannot occur, no matter the value of EnableBitCount
                RtlZeroMemory(Ctx->EnableBitMask, (((Ctx->EnableBitsCount - 1) / 32) + 1) * sizeof(ULONG));
            }
            break;

        default:
            break;
    }

#ifdef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    //
    // Call user defined callback
    //
    MCGEN_PRIVATE_ENABLE_CALLBACK_V2(
        SourceId,
        ControlCode,
        Level,
        MatchAnyKeyword,
        MatchAllKeyword,
        FilterData,
        CallbackContext
        );
#endif // MCGEN_PRIVATE_ENABLE_CALLBACK_V2

    return;
}

#endif // MCGEN_CONTROL_CALLBACK

#ifndef _mcgen_PENABLECALLBACK
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define _mcgen_PENABLECALLBACK      PETWENABLECALLBACK
  #else
    #define _mcgen_PENABLECALLBACK      PENABLECALLBACK
  #endif
#endif // _mcgen_PENABLECALLBACK

#if !defined(_mcgen_PASTE2)
// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_PASTE2(a, b) _mcgen_PASTE2_imp(a, b)
#define _mcgen_PASTE2_imp(a, b) a##b
#endif // _mcgen_PASTE2

#if !defined(_mcgen_PASTE3)
// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_PASTE3(a, b, c) _mcgen_PASTE3_imp(a, b, c)
#define _mcgen_PASTE3_imp(a, b, c) a##b##_##c
#endif // _mcgen_PASTE3

//
// Macro validation
//

// Validate MCGEN_EVENTREGISTER:

// Trigger an error if MCGEN_EVENTREGISTER is not an unqualified (simple) identifier:
struct _mcgen_PASTE2(MCGEN_EVENTREGISTER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTREGISTER);

// Trigger an error if MCGEN_EVENTREGISTER is redefined:
typedef struct _mcgen_PASTE2(MCGEN_EVENTREGISTER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTREGISTER)
    MCGEN_EVENTREGISTER_must_not_be_redefined_between_headers;

// Trigger an error if MCGEN_EVENTREGISTER is defined as a function-like macro:
typedef void MCGEN_EVENTREGISTER_must_not_be_a_functionLike_macro_MCGEN_EVENTREGISTER;
typedef int _mcgen_PASTE2(MCGEN_EVENTREGISTER_must_not_be_a_functionLike_macro_, MCGEN_EVENTREGISTER);

// Validate MCGEN_EVENTUNREGISTER:

// Trigger an error if MCGEN_EVENTUNREGISTER is not an unqualified (simple) identifier:
struct _mcgen_PASTE2(MCGEN_EVENTUNREGISTER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTUNREGISTER);

// Trigger an error if MCGEN_EVENTUNREGISTER is redefined:
typedef struct _mcgen_PASTE2(MCGEN_EVENTUNREGISTER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTUNREGISTER)
    MCGEN_EVENTUNREGISTER_must_not_be_redefined_between_headers;

// Trigger an error if MCGEN_EVENTUNREGISTER is defined as a function-like macro:
typedef void MCGEN_EVENTUNREGISTER_must_not_be_a_functionLike_macro_MCGEN_EVENTUNREGISTER;
typedef int _mcgen_PASTE2(MCGEN_EVENTUNREGISTER_must_not_be_a_functionLike_macro_, MCGEN_EVENTUNREGISTER);

// Validate MCGEN_EVENTSETINFORMATION:

// Trigger an error if MCGEN_EVENTSETINFORMATION is not an unqualified (simple) identifier:
struct _mcgen_PASTE2(MCGEN_EVENTSETINFORMATION_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTSETINFORMATION);

// Trigger an error if MCGEN_EVENTSETINFORMATION is redefined:
typedef struct _mcgen_PASTE2(MCGEN_EVENTSETINFORMATION_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTSETINFORMATION)
    MCGEN_EVENTSETINFORMATION_must_not_be_redefined_between_headers;

// Trigger an error if MCGEN_EVENTSETINFORMATION is defined as a function-like macro:
typedef void MCGEN_EVENTSETINFORMATION_must_not_be_a_functionLike_macro_MCGEN_EVENTSETINFORMATION;
typedef int _mcgen_PASTE2(MCGEN_EVENTSETINFORMATION_must_not_be_a_functionLike_macro_, MCGEN_EVENTSETINFORMATION);

// Validate MCGEN_EVENTWRITETRANSFER:

// Trigger an error if MCGEN_EVENTWRITETRANSFER is not an unqualified (simple) identifier:
struct _mcgen_PASTE2(MCGEN_EVENTWRITETRANSFER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTWRITETRANSFER);

// Trigger an error if MCGEN_EVENTWRITETRANSFER is redefined:
typedef struct _mcgen_PASTE2(MCGEN_EVENTWRITETRANSFER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTWRITETRANSFER)
    MCGEN_EVENTWRITETRANSFER_must_not_be_redefined_between_headers;;

// Trigger an error if MCGEN_EVENTWRITETRANSFER is defined as a function-like macro:
typedef void MCGEN_EVENTWRITETRANSFER_must_not_be_a_functionLike_macro_MCGEN_EVENTWRITETRANSFER;
typedef int _mcgen_PASTE2(MCGEN_EVENTWRITETRANSFER_must_not_be_a_functionLike_macro_, MCGEN_EVENTWRITETRANSFER);

#ifndef McGenEventWrite_def
#define McGenEventWrite_def

// This macro is for use by MC-generated code and should not be used directly.
#define McGenEventWrite _mcgen_PASTE2(McGenEventWrite_, MCGEN_EVENTWRITETRANSFER)

// This function is for use by MC-generated code and should not be used directly.
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventWrite(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ LPCGUID ActivityId,
    _In_range_(1, 128) ULONG EventDataCount,
    _Pre_cap_(EventDataCount) EVENT_DATA_DESCRIPTOR* EventData
    )
{
    const USHORT UNALIGNED* Traits;

    // Some customized MCGEN_EVENTWRITETRANSFER macros might ignore ActivityId.
    UNREFERENCED_PARAMETER(ActivityId);

    Traits = (const USHORT UNALIGNED*)(UINT_PTR)Context->Logger;

    if (Traits == NULL) {
        EventData[0].Ptr = 0;
        EventData[0].Size = 0;
        EventData[0].Reserved = 0;
    } else {
        EventData[0].Ptr = (ULONG_PTR)Traits;
        EventData[0].Size = *Traits;
        EventData[0].Reserved = 2; // EVENT_DATA_DESCRIPTOR_TYPE_PROVIDER_METADATA
    }

    return MCGEN_EVENTWRITETRANSFER(
        Context->RegistrationHandle,
        Descriptor,
        ActivityId,
        NULL,
        EventDataCount,
        EventData);
}
#endif // McGenEventWrite_def

#if !defined(McGenEventRegisterUnregister)
#define McGenEventRegisterUnregister

// This macro is for use by MC-generated code and should not be used directly.
#define McGenEventRegister _mcgen_PASTE2(McGenEventRegister_, MCGEN_EVENTREGISTER)

#pragma warning(push)
#pragma warning(disable:6103)
// This function is for use by MC-generated code and should not be used directly.
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventRegister(
    _In_ LPCGUID ProviderId,
    _In_opt_ _mcgen_PENABLECALLBACK EnableCallback,
    _In_opt_ PVOID CallbackContext,
    _Inout_ PREGHANDLE RegHandle
    )
/*++

Routine Description:

    This function registers the provider with ETW.

Arguments:

    ProviderId - Provider ID to register with ETW.

    EnableCallback - Callback to be used.

    CallbackContext - Context for the callback.

    RegHandle - Pointer to registration handle.

Remarks:

    Should not be called if the provider is already registered (i.e. should not
    be called if *RegHandle != 0). Repeatedly registering a provider is a bug
    and may indicate a race condition. However, for compatibility with previous
    behavior, this function will return SUCCESS in this case.

--*/
{
    ULONG Error;

    if (*RegHandle != 0)
    {
        Error = 0; // ERROR_SUCCESS
    }
    else
    {
        Error = MCGEN_EVENTREGISTER(ProviderId, EnableCallback, CallbackContext, RegHandle);
    }

    return Error;
}
#pragma warning(pop)

// This macro is for use by MC-generated code and should not be used directly.
#define McGenEventUnregister _mcgen_PASTE2(McGenEventUnregister_, MCGEN_EVENTUNREGISTER)

// This function is for use by MC-generated code and should not be used directly.
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventUnregister(_Inout_ PREGHANDLE RegHandle)
/*++

Routine Description:

    Unregister from ETW and set *RegHandle = 0.

Arguments:

    RegHandle - the pointer to the provider registration handle

Remarks:

    If provider has not been registered (i.e. if *RegHandle == 0),
    return SUCCESS. It is safe to call McGenEventUnregister even if the
    call to McGenEventRegister returned an error.

--*/
{
    ULONG Error;

    if(*RegHandle == 0)
    {
        Error = 0; // ERROR_SUCCESS
    }
    else
    {
        Error = MCGEN_EVENTUNREGISTER(*RegHandle);
        *RegHandle = (REGHANDLE)0;
    }

    return Error;
}

#endif // McGenEventRegisterUnregister

#ifndef _mcgen_EVENT_BIT_SET
  #if defined(_M_IX86) || defined(_M_X64)
    // This macro is for use by MC-generated code and should not be used directly.
    #define _mcgen_EVENT_BIT_SET(EnableBits, BitPosition) ((((const unsigned char*)EnableBits)[BitPosition >> 3] & (1u << (BitPosition & 7))) != 0)
  #else // CPU type
    // This macro is for use by MC-generated code and should not be used directly.
    #define _mcgen_EVENT_BIT_SET(EnableBits, BitPosition) ((EnableBits[BitPosition >> 5] & (1u << (BitPosition & 31))) != 0)
  #endif // CPU type
#endif // _mcgen_EVENT_BIT_SET

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "W3WProtect" event count 12
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = c4b1b7f8-0093-4c96-9444-3eca5bb6174e
EXTERN_C __declspec(selectany) const GUID W3WProtect = {0xc4b1b7f8, 0x0093, 0x4c96, {0x94, 0x44, 0x3e, 0xca, 0x5b, 0xb6, 0x17, 0x4e}};

#ifndef W3WProtect_Traits
#define W3WProtect_Traits NULL
#endif // W3WProtect_Traits

//
// Channel
//
#define w3wprotect 0x10

//
// Tasks
//
#define TASK_W3WPROTECT_ENFORCE 0xa
#define TASK_W3WPROTECT_PASSIVE 0xb

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR ProcessCreationBlock_Enforced = {0x3e9, 0x1, 0x10, 0x3, 0x0, 0xa, 0x8000000000000000};
#define ProcessCreationBlock_Enforced_value 0x3e9
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR ProcessCreationBlock_Passive = {0x3ea, 0x1, 0x10, 0x3, 0x0, 0xb, 0x8000000000000000};
#define ProcessCreationBlock_Passive_value 0x3ea
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FileWriteBlock_Enforced = {0x3eb, 0x1, 0x10, 0x3, 0x0, 0xa, 0x8000000000000000};
#define FileWriteBlock_Enforced_value 0x3eb
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FileWriteBlock_Passive = {0x3ec, 0x1, 0x10, 0x3, 0x0, 0xb, 0x8000000000000000};
#define FileWriteBlock_Passive_value 0x3ec
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FileCreateBlock_Enforced = {0x3ed, 0x1, 0x10, 0x3, 0x0, 0xa, 0x8000000000000000};
#define FileCreateBlock_Enforced_value 0x3ed
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FileCreateBlock_Passive = {0x3ee, 0x1, 0x10, 0x3, 0x0, 0xb, 0x8000000000000000};
#define FileCreateBlock_Passive_value 0x3ee
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR RegSetValueBlock_Enforced = {0x3ef, 0x1, 0x10, 0x3, 0x0, 0xa, 0x8000000000000000};
#define RegSetValueBlock_Enforced_value 0x3ef
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR RegSetValueBlock_Passive = {0x3f1, 0x1, 0x10, 0x3, 0x0, 0xb, 0x8000000000000000};
#define RegSetValueBlock_Passive_value 0x3f1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR W3WProtect_Load = {0x44c, 0x1, 0x10, 0x4, 0x0, 0x0, 0x8000000000000000};
#define W3WProtect_Load_value 0x44c
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR W3WProtect_Unload = {0x44d, 0x1, 0x10, 0x4, 0x0, 0x0, 0x8000000000000000};
#define W3WProtect_Unload_value 0x44d
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR W3WProtect_Config_Updated = {0x44e, 0x1, 0x10, 0x4, 0x0, 0x0, 0x8000000000000000};
#define W3WProtect_Config_Updated_value 0x44e
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR W3WProtect_Config_FailedToLoad = {0x44f, 0x1, 0x10, 0x2, 0x0, 0x0, 0x8000000000000000};
#define W3WProtect_Config_FailedToLoad_value 0x44f

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Event Enablement Bits
// These variables are for use by MC-generated code and should not be used directly.
//
EXTERN_C __declspec(selectany) DECLSPEC_CACHEALIGN ULONG W3WProtectEnableBits[1];
EXTERN_C __declspec(selectany) const ULONGLONG W3WProtectKeywords[3] = {0x8000000000000000, 0x8000000000000000, 0x8000000000000000};
EXTERN_C __declspec(selectany) const unsigned char W3WProtectLevels[3] = {3, 4, 2};

//
// Provider context
//
EXTERN_C __declspec(selectany) MCGEN_TRACE_CONTEXT W3WProtect_Context = {0, (ULONG_PTR)W3WProtect_Traits, 0, 0, 0, 0, 0, 0, 3, W3WProtectEnableBits, W3WProtectKeywords, W3WProtectLevels};

//
// Provider REGHANDLE
//
#define W3WProtectHandle (W3WProtect_Context.RegistrationHandle)

//
// This macro is set to 1, indicating that the EventWrite[Name] macros
// have an Activity parameter. This is controlled by the -km and -um options.
//
#define W3WProtect_EventWriteActivity 1

//
// Register with ETW using the control GUID specified in the manifest.
// Invoke this macro during module initialization (i.e. program startup,
// DLL process attach, or driver load) to initialize the provider.
// Note that if this function returns an error, the error means that
// will not work, but no action needs to be taken -- even if EventRegister
// returns an error, it is generally safe to use EventWrite and
// EventUnregister macros (they will be no-ops if EventRegister failed).
//
#ifndef EventRegisterW3WProtect
#define EventRegisterW3WProtect() McGenEventRegister(&W3WProtect, McGenControlCallbackV2, &W3WProtect_Context, &W3WProtectHandle)
#endif

//
// Register with ETW using a specific control GUID (i.e. a GUID other than what
// is specified in the manifest). Advanced scenarios only.
//
#ifndef EventRegisterByGuidW3WProtect
#define EventRegisterByGuidW3WProtect(Guid) McGenEventRegister(&(Guid), McGenControlCallbackV2, &W3WProtect_Context, &W3WProtectHandle)
#endif

//
// Unregister with ETW and close the provider.
// Invoke this macro during module shutdown (i.e. program exit, DLL process
// detach, or driver unload) to unregister the provider.
// Note that you MUST call EventUnregister before DLL or driver unload
// (not optional): failure to unregister a provider before DLL or driver unload
// will result in crashes.
//
#ifndef EventUnregisterW3WProtect
#define EventUnregisterW3WProtect() McGenEventUnregister(&W3WProtectHandle)
#endif

//
// MCGEN_ENABLE_FORCONTEXT_CODE_GENERATION macro:
// Define this macro to enable support for caller-allocated provider context.
//
#ifdef MCGEN_ENABLE_FORCONTEXT_CODE_GENERATION

//
// Advanced scenarios: Caller-allocated provider context.
// Use when multiple differently-configured provider handles are needed,
// e.g. for container-aware drivers, one context per container.
//
// Usage:
//
// - Caller enables the feature before including this header, e.g.
//   #define MCGEN_ENABLE_FORCONTEXT_CODE_GENERATION 1
// - Caller allocates memory, e.g. pContext = malloc(sizeof(McGenContext_W3WProtect));
// - Caller registers the provider, e.g. EventRegisterW3WProtect_ForContext(pContext);
// - Caller writes events, e.g. EventWriteMyEvent_ForContext(pContext, ...);
// - Caller unregisters, e.g. EventUnregisterW3WProtect_ForContext(pContext);
// - Caller frees memory, e.g. free(pContext);
//

typedef struct tagMcGenContext_W3WProtect {
    // The fields of this structure are subject to change and should
    // not be accessed directly. To access the provider's REGHANDLE,
    // use W3WProtectHandle_ForContext(pContext).
    MCGEN_TRACE_CONTEXT Context;
    ULONG EnableBits[1];
} McGenContext_W3WProtect;

#define EventRegisterW3WProtect_ForContext(pContext)             _mcgen_PASTE2(_mcgen_RegisterForContext_W3WProtect_, MCGEN_EVENTREGISTER)(&W3WProtect, pContext)
#define EventRegisterByGuidW3WProtect_ForContext(Guid, pContext) _mcgen_PASTE2(_mcgen_RegisterForContext_W3WProtect_, MCGEN_EVENTREGISTER)(&(Guid), pContext)
#define EventUnregisterW3WProtect_ForContext(pContext)           McGenEventUnregister(&(pContext)->Context.RegistrationHandle)

//
// Provider REGHANDLE for caller-allocated context.
//
#define W3WProtectHandle_ForContext(pContext) ((pContext)->Context.RegistrationHandle)

// This function is for use by MC-generated code and should not be used directly.
// Initialize and register the caller-allocated context.
__inline
ULONG __stdcall
_mcgen_PASTE2(_mcgen_RegisterForContext_W3WProtect_, MCGEN_EVENTREGISTER)(
    _In_ LPCGUID pProviderId,
    _Out_ McGenContext_W3WProtect* pContext)
{
    RtlZeroMemory(pContext, sizeof(*pContext));
    pContext->Context.Logger = (ULONG_PTR)W3WProtect_Traits;
    pContext->Context.EnableBitsCount = 3;
    pContext->Context.EnableBitMask = pContext->EnableBits;
    pContext->Context.EnableKeyWords = W3WProtectKeywords;
    pContext->Context.EnableLevel = W3WProtectLevels;
    return McGenEventRegister(
        pProviderId,
        McGenControlCallbackV2,
        &pContext->Context,
        &pContext->Context.RegistrationHandle);
}

// This function is for use by MC-generated code and should not be used directly.
// Trigger a compile error if called with the wrong parameter type.
FORCEINLINE
_Ret_ McGenContext_W3WProtect*
_mcgen_CheckContextType_W3WProtect(_In_ McGenContext_W3WProtect* pContext)
{
    return pContext;
}

#endif // MCGEN_ENABLE_FORCONTEXT_CODE_GENERATION

//
// Enablement check macro for event "ProcessCreationBlock_Enforced"
//
#define EventEnabledProcessCreationBlock_Enforced() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 0)
#define EventEnabledProcessCreationBlock_Enforced_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 0)

//
// Event write macros for event "ProcessCreationBlock_Enforced"
//
#define EventWriteProcessCreationBlock_Enforced(Activity, ProcessId, ProcessName, ParentProcessId, CommandLine) \
        MCGEN_EVENT_ENABLED(ProcessCreationBlock_Enforced) \
        ? _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Enforced(&W3WProtect_Context, &ProcessCreationBlock_Enforced, Activity, ProcessId, ProcessName, ParentProcessId, CommandLine) : 0
#define EventWriteProcessCreationBlock_Enforced_AssumeEnabled(ProcessId, ProcessName, ParentProcessId, CommandLine) \
        _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Enforced(&W3WProtect_Context, &ProcessCreationBlock_Enforced, NULL, ProcessId, ProcessName, ParentProcessId, CommandLine)
#define EventWriteProcessCreationBlock_Enforced_ForContext(pContext, Activity, ProcessId, ProcessName, ParentProcessId, CommandLine) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, ProcessCreationBlock_Enforced) \
        ? _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Enforced(&(pContext)->Context, &ProcessCreationBlock_Enforced, Activity, ProcessId, ProcessName, ParentProcessId, CommandLine) : 0
#define EventWriteProcessCreationBlock_Enforced_ForContextAssumeEnabled(pContext, ProcessId, ProcessName, ParentProcessId, CommandLine) \
        _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Enforced(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &ProcessCreationBlock_Enforced, NULL, ProcessId, ProcessName, ParentProcessId, CommandLine)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Enforced _mcgen_PASTE2(McTemplateK0qzqz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "ProcessCreationBlock_Passive"
//
#define EventEnabledProcessCreationBlock_Passive() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 0)
#define EventEnabledProcessCreationBlock_Passive_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 0)

//
// Event write macros for event "ProcessCreationBlock_Passive"
//
#define EventWriteProcessCreationBlock_Passive(Activity, ProcessId, ProcessName, ParentProcessId, CommandLine) \
        MCGEN_EVENT_ENABLED(ProcessCreationBlock_Passive) \
        ? _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Passive(&W3WProtect_Context, &ProcessCreationBlock_Passive, Activity, ProcessId, ProcessName, ParentProcessId, CommandLine) : 0
#define EventWriteProcessCreationBlock_Passive_AssumeEnabled(ProcessId, ProcessName, ParentProcessId, CommandLine) \
        _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Passive(&W3WProtect_Context, &ProcessCreationBlock_Passive, NULL, ProcessId, ProcessName, ParentProcessId, CommandLine)
#define EventWriteProcessCreationBlock_Passive_ForContext(pContext, Activity, ProcessId, ProcessName, ParentProcessId, CommandLine) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, ProcessCreationBlock_Passive) \
        ? _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Passive(&(pContext)->Context, &ProcessCreationBlock_Passive, Activity, ProcessId, ProcessName, ParentProcessId, CommandLine) : 0
#define EventWriteProcessCreationBlock_Passive_ForContextAssumeEnabled(pContext, ProcessId, ProcessName, ParentProcessId, CommandLine) \
        _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Passive(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &ProcessCreationBlock_Passive, NULL, ProcessId, ProcessName, ParentProcessId, CommandLine)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_ProcessCreationBlock_Passive _mcgen_PASTE2(McTemplateK0qzqz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "FileWriteBlock_Enforced"
//
#define EventEnabledFileWriteBlock_Enforced() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 0)
#define EventEnabledFileWriteBlock_Enforced_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 0)

//
// Event write macros for event "FileWriteBlock_Enforced"
//
#define EventWriteFileWriteBlock_Enforced(Activity, ProcessId, Filename, ParentDirectory) \
        MCGEN_EVENT_ENABLED(FileWriteBlock_Enforced) \
        ? _mcgen_TEMPLATE_FOR_FileWriteBlock_Enforced(&W3WProtect_Context, &FileWriteBlock_Enforced, Activity, ProcessId, Filename, ParentDirectory) : 0
#define EventWriteFileWriteBlock_Enforced_AssumeEnabled(ProcessId, Filename, ParentDirectory) \
        _mcgen_TEMPLATE_FOR_FileWriteBlock_Enforced(&W3WProtect_Context, &FileWriteBlock_Enforced, NULL, ProcessId, Filename, ParentDirectory)
#define EventWriteFileWriteBlock_Enforced_ForContext(pContext, Activity, ProcessId, Filename, ParentDirectory) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, FileWriteBlock_Enforced) \
        ? _mcgen_TEMPLATE_FOR_FileWriteBlock_Enforced(&(pContext)->Context, &FileWriteBlock_Enforced, Activity, ProcessId, Filename, ParentDirectory) : 0
#define EventWriteFileWriteBlock_Enforced_ForContextAssumeEnabled(pContext, ProcessId, Filename, ParentDirectory) \
        _mcgen_TEMPLATE_FOR_FileWriteBlock_Enforced(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &FileWriteBlock_Enforced, NULL, ProcessId, Filename, ParentDirectory)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_FileWriteBlock_Enforced _mcgen_PASTE2(McTemplateK0qzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "FileWriteBlock_Passive"
//
#define EventEnabledFileWriteBlock_Passive() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 0)
#define EventEnabledFileWriteBlock_Passive_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 0)

//
// Event write macros for event "FileWriteBlock_Passive"
//
#define EventWriteFileWriteBlock_Passive(Activity, ProcessId, Filename, ParentDirectory) \
        MCGEN_EVENT_ENABLED(FileWriteBlock_Passive) \
        ? _mcgen_TEMPLATE_FOR_FileWriteBlock_Passive(&W3WProtect_Context, &FileWriteBlock_Passive, Activity, ProcessId, Filename, ParentDirectory) : 0
#define EventWriteFileWriteBlock_Passive_AssumeEnabled(ProcessId, Filename, ParentDirectory) \
        _mcgen_TEMPLATE_FOR_FileWriteBlock_Passive(&W3WProtect_Context, &FileWriteBlock_Passive, NULL, ProcessId, Filename, ParentDirectory)
#define EventWriteFileWriteBlock_Passive_ForContext(pContext, Activity, ProcessId, Filename, ParentDirectory) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, FileWriteBlock_Passive) \
        ? _mcgen_TEMPLATE_FOR_FileWriteBlock_Passive(&(pContext)->Context, &FileWriteBlock_Passive, Activity, ProcessId, Filename, ParentDirectory) : 0
#define EventWriteFileWriteBlock_Passive_ForContextAssumeEnabled(pContext, ProcessId, Filename, ParentDirectory) \
        _mcgen_TEMPLATE_FOR_FileWriteBlock_Passive(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &FileWriteBlock_Passive, NULL, ProcessId, Filename, ParentDirectory)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_FileWriteBlock_Passive _mcgen_PASTE2(McTemplateK0qzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "FileCreateBlock_Enforced"
//
#define EventEnabledFileCreateBlock_Enforced() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 0)
#define EventEnabledFileCreateBlock_Enforced_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 0)

//
// Event write macros for event "FileCreateBlock_Enforced"
//
#define EventWriteFileCreateBlock_Enforced(Activity, ProcessId, Filename, ParentDirectory) \
        MCGEN_EVENT_ENABLED(FileCreateBlock_Enforced) \
        ? _mcgen_TEMPLATE_FOR_FileCreateBlock_Enforced(&W3WProtect_Context, &FileCreateBlock_Enforced, Activity, ProcessId, Filename, ParentDirectory) : 0
#define EventWriteFileCreateBlock_Enforced_AssumeEnabled(ProcessId, Filename, ParentDirectory) \
        _mcgen_TEMPLATE_FOR_FileCreateBlock_Enforced(&W3WProtect_Context, &FileCreateBlock_Enforced, NULL, ProcessId, Filename, ParentDirectory)
#define EventWriteFileCreateBlock_Enforced_ForContext(pContext, Activity, ProcessId, Filename, ParentDirectory) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, FileCreateBlock_Enforced) \
        ? _mcgen_TEMPLATE_FOR_FileCreateBlock_Enforced(&(pContext)->Context, &FileCreateBlock_Enforced, Activity, ProcessId, Filename, ParentDirectory) : 0
#define EventWriteFileCreateBlock_Enforced_ForContextAssumeEnabled(pContext, ProcessId, Filename, ParentDirectory) \
        _mcgen_TEMPLATE_FOR_FileCreateBlock_Enforced(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &FileCreateBlock_Enforced, NULL, ProcessId, Filename, ParentDirectory)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_FileCreateBlock_Enforced _mcgen_PASTE2(McTemplateK0qzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "FileCreateBlock_Passive"
//
#define EventEnabledFileCreateBlock_Passive() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 0)
#define EventEnabledFileCreateBlock_Passive_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 0)

//
// Event write macros for event "FileCreateBlock_Passive"
//
#define EventWriteFileCreateBlock_Passive(Activity, ProcessId, Filename, ParentDirectory) \
        MCGEN_EVENT_ENABLED(FileCreateBlock_Passive) \
        ? _mcgen_TEMPLATE_FOR_FileCreateBlock_Passive(&W3WProtect_Context, &FileCreateBlock_Passive, Activity, ProcessId, Filename, ParentDirectory) : 0
#define EventWriteFileCreateBlock_Passive_AssumeEnabled(ProcessId, Filename, ParentDirectory) \
        _mcgen_TEMPLATE_FOR_FileCreateBlock_Passive(&W3WProtect_Context, &FileCreateBlock_Passive, NULL, ProcessId, Filename, ParentDirectory)
#define EventWriteFileCreateBlock_Passive_ForContext(pContext, Activity, ProcessId, Filename, ParentDirectory) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, FileCreateBlock_Passive) \
        ? _mcgen_TEMPLATE_FOR_FileCreateBlock_Passive(&(pContext)->Context, &FileCreateBlock_Passive, Activity, ProcessId, Filename, ParentDirectory) : 0
#define EventWriteFileCreateBlock_Passive_ForContextAssumeEnabled(pContext, ProcessId, Filename, ParentDirectory) \
        _mcgen_TEMPLATE_FOR_FileCreateBlock_Passive(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &FileCreateBlock_Passive, NULL, ProcessId, Filename, ParentDirectory)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_FileCreateBlock_Passive _mcgen_PASTE2(McTemplateK0qzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "RegSetValueBlock_Enforced"
//
#define EventEnabledRegSetValueBlock_Enforced() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 0)
#define EventEnabledRegSetValueBlock_Enforced_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 0)

//
// Event write macros for event "RegSetValueBlock_Enforced"
//
#define EventWriteRegSetValueBlock_Enforced(Activity, RegistryValue) \
        MCGEN_EVENT_ENABLED(RegSetValueBlock_Enforced) \
        ? _mcgen_TEMPLATE_FOR_RegSetValueBlock_Enforced(&W3WProtect_Context, &RegSetValueBlock_Enforced, Activity, RegistryValue) : 0
#define EventWriteRegSetValueBlock_Enforced_AssumeEnabled(RegistryValue) \
        _mcgen_TEMPLATE_FOR_RegSetValueBlock_Enforced(&W3WProtect_Context, &RegSetValueBlock_Enforced, NULL, RegistryValue)
#define EventWriteRegSetValueBlock_Enforced_ForContext(pContext, Activity, RegistryValue) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, RegSetValueBlock_Enforced) \
        ? _mcgen_TEMPLATE_FOR_RegSetValueBlock_Enforced(&(pContext)->Context, &RegSetValueBlock_Enforced, Activity, RegistryValue) : 0
#define EventWriteRegSetValueBlock_Enforced_ForContextAssumeEnabled(pContext, RegistryValue) \
        _mcgen_TEMPLATE_FOR_RegSetValueBlock_Enforced(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &RegSetValueBlock_Enforced, NULL, RegistryValue)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_RegSetValueBlock_Enforced _mcgen_PASTE2(McTemplateK0z_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "RegSetValueBlock_Passive"
//
#define EventEnabledRegSetValueBlock_Passive() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 0)
#define EventEnabledRegSetValueBlock_Passive_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 0)

//
// Event write macros for event "RegSetValueBlock_Passive"
//
#define EventWriteRegSetValueBlock_Passive(Activity, RegistryValue) \
        MCGEN_EVENT_ENABLED(RegSetValueBlock_Passive) \
        ? _mcgen_TEMPLATE_FOR_RegSetValueBlock_Passive(&W3WProtect_Context, &RegSetValueBlock_Passive, Activity, RegistryValue) : 0
#define EventWriteRegSetValueBlock_Passive_AssumeEnabled(RegistryValue) \
        _mcgen_TEMPLATE_FOR_RegSetValueBlock_Passive(&W3WProtect_Context, &RegSetValueBlock_Passive, NULL, RegistryValue)
#define EventWriteRegSetValueBlock_Passive_ForContext(pContext, Activity, RegistryValue) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, RegSetValueBlock_Passive) \
        ? _mcgen_TEMPLATE_FOR_RegSetValueBlock_Passive(&(pContext)->Context, &RegSetValueBlock_Passive, Activity, RegistryValue) : 0
#define EventWriteRegSetValueBlock_Passive_ForContextAssumeEnabled(pContext, RegistryValue) \
        _mcgen_TEMPLATE_FOR_RegSetValueBlock_Passive(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &RegSetValueBlock_Passive, NULL, RegistryValue)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_RegSetValueBlock_Passive _mcgen_PASTE2(McTemplateK0z_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "W3WProtect_Load"
//
#define EventEnabledW3WProtect_Load() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 1)
#define EventEnabledW3WProtect_Load_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 1)

//
// Event write macros for event "W3WProtect_Load"
//
#define EventWriteW3WProtect_Load(Activity) \
        MCGEN_EVENT_ENABLED(W3WProtect_Load) \
        ? _mcgen_TEMPLATE_FOR_W3WProtect_Load(&W3WProtect_Context, &W3WProtect_Load, Activity) : 0
#define EventWriteW3WProtect_Load_AssumeEnabled() \
        _mcgen_TEMPLATE_FOR_W3WProtect_Load(&W3WProtect_Context, &W3WProtect_Load, NULL)
#define EventWriteW3WProtect_Load_ForContext(pContext, Activity) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, W3WProtect_Load) \
        ? _mcgen_TEMPLATE_FOR_W3WProtect_Load(&(pContext)->Context, &W3WProtect_Load, Activity) : 0
#define EventWriteW3WProtect_Load_ForContextAssumeEnabled(pContext) \
        _mcgen_TEMPLATE_FOR_W3WProtect_Load(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &W3WProtect_Load, NULL)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_W3WProtect_Load _mcgen_PASTE2(McTemplateK0_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "W3WProtect_Unload"
//
#define EventEnabledW3WProtect_Unload() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 1)
#define EventEnabledW3WProtect_Unload_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 1)

//
// Event write macros for event "W3WProtect_Unload"
//
#define EventWriteW3WProtect_Unload(Activity) \
        MCGEN_EVENT_ENABLED(W3WProtect_Unload) \
        ? _mcgen_TEMPLATE_FOR_W3WProtect_Unload(&W3WProtect_Context, &W3WProtect_Unload, Activity) : 0
#define EventWriteW3WProtect_Unload_AssumeEnabled() \
        _mcgen_TEMPLATE_FOR_W3WProtect_Unload(&W3WProtect_Context, &W3WProtect_Unload, NULL)
#define EventWriteW3WProtect_Unload_ForContext(pContext, Activity) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, W3WProtect_Unload) \
        ? _mcgen_TEMPLATE_FOR_W3WProtect_Unload(&(pContext)->Context, &W3WProtect_Unload, Activity) : 0
#define EventWriteW3WProtect_Unload_ForContextAssumeEnabled(pContext) \
        _mcgen_TEMPLATE_FOR_W3WProtect_Unload(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &W3WProtect_Unload, NULL)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_W3WProtect_Unload _mcgen_PASTE2(McTemplateK0_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "W3WProtect_Config_Updated"
//
#define EventEnabledW3WProtect_Config_Updated() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 1)
#define EventEnabledW3WProtect_Config_Updated_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 1)

//
// Event write macros for event "W3WProtect_Config_Updated"
//
#define EventWriteW3WProtect_Config_Updated(Activity) \
        MCGEN_EVENT_ENABLED(W3WProtect_Config_Updated) \
        ? _mcgen_TEMPLATE_FOR_W3WProtect_Config_Updated(&W3WProtect_Context, &W3WProtect_Config_Updated, Activity) : 0
#define EventWriteW3WProtect_Config_Updated_AssumeEnabled() \
        _mcgen_TEMPLATE_FOR_W3WProtect_Config_Updated(&W3WProtect_Context, &W3WProtect_Config_Updated, NULL)
#define EventWriteW3WProtect_Config_Updated_ForContext(pContext, Activity) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, W3WProtect_Config_Updated) \
        ? _mcgen_TEMPLATE_FOR_W3WProtect_Config_Updated(&(pContext)->Context, &W3WProtect_Config_Updated, Activity) : 0
#define EventWriteW3WProtect_Config_Updated_ForContextAssumeEnabled(pContext) \
        _mcgen_TEMPLATE_FOR_W3WProtect_Config_Updated(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &W3WProtect_Config_Updated, NULL)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_W3WProtect_Config_Updated _mcgen_PASTE2(McTemplateK0_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "W3WProtect_Config_FailedToLoad"
//
#define EventEnabledW3WProtect_Config_FailedToLoad() _mcgen_EVENT_BIT_SET(W3WProtectEnableBits, 2)
#define EventEnabledW3WProtect_Config_FailedToLoad_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_W3WProtect(pContext)->EnableBits, 2)

//
// Event write macros for event "W3WProtect_Config_FailedToLoad"
//
#define EventWriteW3WProtect_Config_FailedToLoad(Activity) \
        MCGEN_EVENT_ENABLED(W3WProtect_Config_FailedToLoad) \
        ? _mcgen_TEMPLATE_FOR_W3WProtect_Config_FailedToLoad(&W3WProtect_Context, &W3WProtect_Config_FailedToLoad, Activity) : 0
#define EventWriteW3WProtect_Config_FailedToLoad_AssumeEnabled() \
        _mcgen_TEMPLATE_FOR_W3WProtect_Config_FailedToLoad(&W3WProtect_Context, &W3WProtect_Config_FailedToLoad, NULL)
#define EventWriteW3WProtect_Config_FailedToLoad_ForContext(pContext, Activity) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, W3WProtect_Config_FailedToLoad) \
        ? _mcgen_TEMPLATE_FOR_W3WProtect_Config_FailedToLoad(&(pContext)->Context, &W3WProtect_Config_FailedToLoad, Activity) : 0
#define EventWriteW3WProtect_Config_FailedToLoad_ForContextAssumeEnabled(pContext) \
        _mcgen_TEMPLATE_FOR_W3WProtect_Config_FailedToLoad(&_mcgen_CheckContextType_W3WProtect(pContext)->Context, &W3WProtect_Config_FailedToLoad, NULL)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_W3WProtect_Config_FailedToLoad _mcgen_PASTE2(McTemplateK0_, MCGEN_EVENTWRITETRANSFER)

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Template Functions
//

//
// Function for template "(default)" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateK0_def
#define McTemplateK0_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateK0_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ const GUID* Activity
    )
{
#define McTemplateK0_ARGCOUNT 0

    EVENT_DATA_DESCRIPTOR EventData[McTemplateK0_ARGCOUNT + 1];

    return McGenEventWrite(Context, Descriptor, Activity, McTemplateK0_ARGCOUNT + 1, EventData);
}
#endif // McTemplateK0_def

//
// Function for template "tid_Process_Block" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateK0qzqz_def
#define McTemplateK0qzqz_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateK0qzqz_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ const GUID* Activity,
    _In_ const unsigned int  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_ const unsigned int  _Arg2,
    _In_opt_ PCWSTR  _Arg3
    )
{
#define McTemplateK0qzqz_ARGCOUNT 4

    EVENT_DATA_DESCRIPTOR EventData[McTemplateK0qzqz_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],&_Arg0, sizeof(const unsigned int)  );

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],&_Arg2, sizeof(const unsigned int)  );

    EventDataDescCreate(&EventData[4],
                        (_Arg3 != NULL) ? _Arg3 : L"NULL",
                        (_Arg3 != NULL) ? (ULONG)((wcslen(_Arg3) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, Activity, McTemplateK0qzqz_ARGCOUNT + 1, EventData);
}
#endif // McTemplateK0qzqz_def

//
// Function for template "tid_File_Block" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateK0qzz_def
#define McTemplateK0qzz_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateK0qzz_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ const GUID* Activity,
    _In_ const unsigned int  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_opt_ PCWSTR  _Arg2
    )
{
#define McTemplateK0qzz_ARGCOUNT 3

    EVENT_DATA_DESCRIPTOR EventData[McTemplateK0qzz_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],&_Arg0, sizeof(const unsigned int)  );

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : L"NULL",
                        (_Arg2 != NULL) ? (ULONG)((wcslen(_Arg2) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, Activity, McTemplateK0qzz_ARGCOUNT + 1, EventData);
}
#endif // McTemplateK0qzz_def

//
// Function for template "tid_Reg_Block" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateK0z_def
#define McTemplateK0z_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateK0z_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ const GUID* Activity,
    _In_opt_ PCWSTR  _Arg0
    )
{
#define McTemplateK0z_ARGCOUNT 1

    EVENT_DATA_DESCRIPTOR EventData[McTemplateK0z_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],
                        (_Arg0 != NULL) ? _Arg0 : L"NULL",
                        (_Arg0 != NULL) ? (ULONG)((wcslen(_Arg0) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, Activity, McTemplateK0z_ARGCOUNT + 1, EventData);
}
#endif // McTemplateK0z_def

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

#if defined(__cplusplus)
}
#endif

#define MSG_Name                             0x90000001L
#define MSG_ProcessCreationBlocked_Enforced  0xB00103E9L
#define MSG_ProcessCreationBlocked_Passive   0xB00103EAL
#define MSG_FileWriteBlock_Enforced          0xB00103EBL
#define MSG_FileWriteBlock_Passive           0xB00103ECL
#define MSG_FileCreateBlock_Enforced         0xB00103EDL
#define MSG_FileCreateBlock_Passive          0xB00103EEL
#define MSG_RegSetValueBlock_Enforced        0xB00103EFL
#define MSG_RegSetValueBlock_Passive         0xB00103F1L
#define MSG_Module_Load                      0xB001044CL
#define MSG_Module_Unload                    0xB001044DL
#define MSG_Config_Updated                   0xB001044EL
#define MSG_Config_FailedToLoad              0xB001044FL
